# video capture configuration
VIDEO_CAPTURE_WIDTH = 1280
VIDEO_CAPTURE_HEIGHT = 720
VIDEO_CAPTURE_FRAMERATE = 60

# color for object recognition
TARGET_RED = 0
TARGET_GREEN = 0
TARGET_BLUE = 0
RECOGNITION_TOLERANCE = 10

# text-to-speech configuration
TTS_VOLUME = 1.0
TTS_WORDS_PER_MINUTE = 150